name: .NET

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # checkout main branch
    - uses: actions/checkout@v3
    
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v2.0.0
      with:
        dotnet-version: 6.0.x
        
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.1.1
    
    # TO DO: this can be improved...
    - name: Compile Sass
      run: |
        npm install -g sass
        sass Site.Wasm/Pages
        sass Site.Wasm/Shared
      
    - name: Publish project
      run: dotnet publish Site.Wasm -o release --nologo

    - name: copy index.html to 404.html
      run: cp release/wwwroot/index.html release/wwwroot/404.html
      
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
      
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.3.0
      with:
        branch: gh-pages
        folder: release/wwwroot
